# Use an official Node runtime as a parent image
FROM node:16

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Bundle app source
COPY . .

# Your app binds to port 3000 so you'll use the EXPOSE instruction to have it mapped by the docker daemon
EXPOSE 8080


# Use ARG to get environment variables at build time
# Declare build-time environment variables
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_TELEGRAM_API_TOKEN
ARG NEXT_PUBLIC_LANDING_URL
ARG NEXT_PUBLIC_META_API_TOKEN
ARG NEXT_PUBLIC_CHARGEBEE_SITE
ARG NEXT_PUBLIC_CHARGEBEE_API_KEY
ARG NEXT_PUBLIC_CHARGEBEE_API_KEY_B
ARG NEXT_PUBLIC_TEST_PROFILE_ID
ARG NEXT_PUBLIC_TEST_WEBHOOKS_LIST_IDS
ARG NEXT_PUBLIC_ALLOWED_EMAILS
ARG NEXT_PUBLIC_KLAVIO_PRIVATE_KEY

# Set environment variables
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_TELEGRAM_API_TOKEN=$NEXT_PUBLIC_TELEGRAM_API_TOKEN
ENV NEXT_PUBLIC_LANDING_URL=$NEXT_PUBLIC_LANDING_URL
ENV NEXT_PUBLIC_META_API_TOKEN=$NEXT_PUBLIC_META_API_TOKEN
ENV NEXT_PUBLIC_CHARGEBEE_SITE=$NEXT_PUBLIC_CHARGEBEE_SITE
ENV NEXT_PUBLIC_CHARGEBEE_API_KEY=$NEXT_PUBLIC_CHARGEBEE_API_KEY
ENV NEXT_PUBLIC_CHARGEBEE_API_KEY_B=$NEXT_PUBLIC_CHARGEBEE_API_KEY_B
ENV NEXT_PUBLIC_TEST_PROFILE_ID=$NEXT_PUBLIC_TEST_PROFILE_ID
ENV NEXT_PUBLIC_TEST_WEBHOOKS_LIST_IDS=$NEXT_PUBLIC_TEST_WEBHOOKS_LIST_IDS
ENV NEXT_PUBLIC_ALLOWED_EMAILS=$NEXT_PUBLIC_ALLOWED_EMAILS
ENV NEXT_PUBLIC_KLAVIO_PRIVATE_KEY=$NEXT_PUBLIC_KLAVIO_PRIVATE_KEY

# Build the app
RUN npm run build

# Define the command to run your app
CMD [ "npm", "start" ]
