export const emailsList = [
  "nidhal.nouma.0@gmail.com",
  "nidhal.nouma.1@gmail.com",
  "automatedtrader@gmail.com",
  "Melaniekers@gmail.com",
  "Cheatcodefx@gmail.com",
  "ddelorenzojr@icloud.com",
  "abbas@afsmholding.se",
  "rcepoudy27@gmail.com",
  "eric.capistrano@gmail.com",
  "ii-vancha-ii@hotmail.com",
  "Burton78@gmail.com",
  "huskog31@gmail.com",
  "bbasson@bellusps.ca",
  "saagar@consultant.com",
];
