export const pricingList = {
  monthly: {
    "Basic plan": {
      paddleId: Number(process.env.NEXT_PUBLIC_PADDLE_PLAN_1),
      price: 29,
      save: 0,
      accounts: 1,
      webhooks: 1,
      telegram: true,
      discord: false,
      shareAlerts: false,
      more: false,
    },
    "Standard plan": {
      paddleId: Number(process.env.NEXT_PUBLIC_PADDLE_PLAN_1),
      price: 49,
      save: 0,
      accounts: 3,
      webhooks: 3,
      telegram: true,
      discord: false,
      shareAlerts: false,
      more: false,
    },
    "Professional plan": {
      paddleId: Number(process.env.NEXT_PUBLIC_PADDLE_PLAN_1),
      price: 99,
      save: 0,
      accounts: 5,
      webhooks: 5,
      telegram: true,
      discord: true,
      shareAlerts: false,
      more: false,
    },
    "Premium plan": {
      paddleId: Number(process.env.NEXT_PUBLIC_PADDLE_PLAN_1),
      price: 159,
      save: 0,
      accounts: 20,
      webhooks: 40,
      telegram: true,
      discord: true,
      shareAlerts: true,
      more: true,
    },
  },
  annual: {
    "Basic plan": {
      paddleId: Number(process.env.NEXT_PUBLIC_PADDLE_PLAN_1),
      price: 243,
      save: 30,
      accounts: 1,
      webhooks: 1,
      telegram: true,
      discord: false,
      shareAlerts: false,
      more: false,
    },
    "Standard plan": {
      paddleId: Number(process.env.NEXT_PUBLIC_PADDLE_PLAN_1),
      price: 411,
      save: 30,
      accounts: 3,
      webhooks: 3,
      telegram: true,
      discord: false,
      shareAlerts: false,
      more: false,
    },
    "Professional plan": {
      paddleId: Number(process.env.NEXT_PUBLIC_PADDLE_PLAN_1),
      price: 712,
      save: 40,
      accounts: 5,
      webhooks: 5,
      telegram: true,
      discord: true,
      shareAlerts: false,
      more: false,
    },
    "Premium plan": {
      paddleId: Number(process.env.NEXT_PUBLIC_PADDLE_PLAN_1),
      price: 954,
      save: 50,
      accounts: 20,
      webhooks: 40,
      telegram: true,
      discord: true,
      shareAlerts: true,
      more: true,
    },
  },
  lifetime: {
    "Lifetime access": {
      paddleId: Number(process.env.NEXT_PUBLIC_PADDLE_PLAN_1),
      price: 2500,
      save: 50,
      accounts: 100,
      webhooks: 100,
      telegram: true,
      discord: true,
      shareAlerts: true,
      more: true,
    },
  },
};
